name: Build, test, lint

on:
  - push
  - pull_request

permissions: read-all

jobs:
  lab2:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14

      - run: opam install . --deps-only --with-test
      - run: opam install zanuda

      - run: opam exec -- dune build @fmt @check @runtest -j4
      - run: opam exec -- dune runtest
      - run: opam exec -- zanuda -dir .
